# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='other.proto',
  package='other',
  syntax='proto3',
  serialized_options=b'Z4github.com/t10471/go-examples/grpc-examples/go/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bother.proto\x12\x05other\"\x1c\n\x0cOtherRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nOtherReply\x12\x0f\n\x07message\x18\x01 \x01(\t2w\n\x05Other\x12\x35\n\tCallOther\x12\x13.other.OtherRequest\x1a\x11.other.OtherReply\"\x00\x12\x37\n\x0b\x43\x61llOtherV2\x12\x13.other.OtherRequest\x1a\x11.other.OtherReply\"\x00\x42\x36Z4github.com/t10471/go-examples/grpc-examples/go/protob\x06proto3'
)




_OTHERREQUEST = _descriptor.Descriptor(
  name='OtherRequest',
  full_name='other.OtherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='other.OtherRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)


_OTHERREPLY = _descriptor.Descriptor(
  name='OtherReply',
  full_name='other.OtherReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='other.OtherReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['OtherRequest'] = _OTHERREQUEST
DESCRIPTOR.message_types_by_name['OtherReply'] = _OTHERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OtherRequest = _reflection.GeneratedProtocolMessageType('OtherRequest', (_message.Message,), {
  'DESCRIPTOR' : _OTHERREQUEST,
  '__module__' : 'other_pb2'
  # @@protoc_insertion_point(class_scope:other.OtherRequest)
  })
_sym_db.RegisterMessage(OtherRequest)

OtherReply = _reflection.GeneratedProtocolMessageType('OtherReply', (_message.Message,), {
  'DESCRIPTOR' : _OTHERREPLY,
  '__module__' : 'other_pb2'
  # @@protoc_insertion_point(class_scope:other.OtherReply)
  })
_sym_db.RegisterMessage(OtherReply)


DESCRIPTOR._options = None

_OTHER = _descriptor.ServiceDescriptor(
  name='Other',
  full_name='other.Other',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallOther',
    full_name='other.Other.CallOther',
    index=0,
    containing_service=None,
    input_type=_OTHERREQUEST,
    output_type=_OTHERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CallOtherV2',
    full_name='other.Other.CallOtherV2',
    index=1,
    containing_service=None,
    input_type=_OTHERREQUEST,
    output_type=_OTHERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OTHER)

DESCRIPTOR.services_by_name['Other'] = _OTHER

# @@protoc_insertion_point(module_scope)
